baseURL = "https://www.adiyudana.com"
title = "Nyoman Adi Yudana"
theme = "dream-plus"
	#Don't use this, only for exampleSite
paginate = 4
enableRobotsTXT = true
disqusShortname = "dream-plus"

#Skip building these files
ignoreFiles = ["content/404.md", "content/about.md", "content/cards/\\.*"]

#Syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
	#Favicon for site
	favicon = "/img/defaultFav.ico"

	#Set whether you're hosting "cards" or "post"
	contentType = "posts"

	siteStartYear = 2018

	[params.author]
		name = "Nyoman Adi Yudana"
		description = "Just a random blog for random stuff, mostly tech-related."
		avatar = "https://1.bp.blogspot.com/-UJbghHbd5GA/X9t79vX-lzI/AAAAAAAAAWQ/KFifms6izsAEDcPFlCnv6cTnMVZuX_aLgCLcBGAsYHQ/s16000/Nyoman%2BAdi%2BYudana.jpg"
		motto = "Learn and Share Your Knowledge"

	[params.features]
		#Enable Twitter Emoji
		twitterEmoji = true
		#Enable Table of Contents
		toc = true
		#Enable share card
		shareCard = true
		#Use custom CSS
		customCSS = ["https://cdn.rawgit.com/UtkarshVerma/hugo-dream-plus/ae11561d/exampleSite/static/css/highlight.css"]

	#Tags settings
	[params.tags]
		enabled = true

	#Categories settings
	[params.categories]
		enabled = true

[social]
	email = "utkarshverma@pm.me"
	github = "UtkarshVerma"
	stackoverflow = "9271608/utkarsh-verma"
	medium = "UtkarshVerma_"
	twitter = "UtkarshVerma_"
[permalinks]
    posts= "/:slug/"
